# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish

on:
  # release:
  #   types: [created]
  push:
    branches:
      - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Enable Corepack
#         run: corepack enable
#       - name: Use Node.js 20.x
#         uses: actions/setup-node@v4
#         with:
#           node-version: "22.x"
#           cache: 'yarn'
#       - name: Install dependencies
#         run: yarn install --immutable
#       - name: Run build
#         run: yarn build

#   publish-npm:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Enable Corepack
#         run: corepack enable
#       - name: Use Node.js 20.x
#         uses: actions/setup-node@v4
#         with:
#           node-version: "22.x"
#           cache: 'yarn'
#       - name: Install dependencies
#         run: yarn install --immutable
#       - name: Run build
#         run: yarn build
#       - run: yarn publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.npm_token}}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run build
        run: yarn build
      - name: Publish package
        run: yarn dlx jsr publish
